name: Publish

on:
  push:
    branches:
      - main
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Generate TTL files
        id: gen_ttls
        run: |
             python -m pip install rdflib numpy
             cd src
             python gen_refdataproject_tensiletest_datasets.py
             python gen_refdataproject_tensiletests.py
             python gen_refdataproject_production.py
             python gen_combined_ttl.py
      - name: Prepare release files
        id: prepare_files
        run: |
             mkdir -p release/resources
             cp src/refdataproject_combined.ttl release/refdataproject.ttl
             cp src/refdataproject_combined.rdf release/refdataproject.rdf
             cat src/resources.txt | xargs -I {} touch src/{}
             cat src/resources.txt | xargs -I {} cp src/{} release/resources/
             python src/.github/workflows/index.html.py -f release/index.html -t ${{ github.event.repository.name }} -o $GITHUB_REPOSITORY_OWNER -n ${{ github.event.repository.name }} -r refdataproject -l src/resources.txt
      - name: Generate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
      - name: Publish to gh-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}