name: Publish

on:
  push:
    branches:
      - main
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Generate TTL files
        id: gen_ttls
        run: |
             python -m pip install rdflib numpy
             cd src
             python gen_refdataproject_tensiletest_datasets.py
             python gen_refdataproject_tensiletests.py
             python gen_refdataproject_production.py
             python gen_combined_ttl.py
      - name: Prepare release files
        id: prepare_files
        run: |
             mkdir -p release/resources
             cp src/refdataproject_combined.ttl release/refdataproject.ttl
             xargs -I {} touch src/{}
             xargs -I {} cp src/{} release/resources/
      - name: Generate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release